import fs from 'fs';

let code = fs.readFileSync('src/contexts/LanguageContext.tsx', 'utf8');

const target = `'Top Tech Companies': {"en":"Top Tech Companies","fr":"Meilleures Entreprises Tech","es":"Mejores Empresas Tech","ar":"أفضل شركات التقنية"},`;
const newTranslations = `'Top Tech Companies': {"en":"Top Tech Companies","fr":"Meilleures Entreprises Tech","es":"Mejores Empresas Tech","ar":"أفضل شركات التقنية"},
    'Visitor Profile': { en: 'Visitor Profile', fr: 'Profil Visiteur', es: 'Perfil de Visitante', ar: 'الملف الشخصي للزائر' },
    'Overview': { en: 'Overview', fr: 'Aperçu', es: 'Visión general', ar: 'نظرة عامة' },
    'Liked': { en: 'Liked', fr: 'Aimés', es: 'Me gusta', ar: 'الإعجابات' },
    'Library': { en: 'Library', fr: 'Bibliothèque', es: 'Biblioteca', ar: 'المكتبة' },
    'Game history': { en: 'Game history', fr: 'Historique des jeux', es: 'Historial de juegos', ar: 'سجل الألعاب' },
    'Favorites': { en: 'Favorites', fr: 'Favoris', es: 'Favoritos', ar: 'المفضلة' },
    'SecretArea Statistics': { en: 'SecretArea Statistics', fr: 'Statistiques SecretArea', es: 'Estadísticas de SecretArea', ar: 'إحصائيات المنطقة السرية' },
    'Total Points Earned': { en: 'Total Points Earned', fr: 'Total des points gagnés', es: 'Puntos totales ganados', ar: 'إجمالي النقاط المكتسبة' },
    'Total Games Viewed': { en: 'Total Games Viewed', fr: 'Total des jeux vus', es: 'Total de juegos vistos', ar: 'إجمالي الألعاب المعروضة' },
    'Content Liked': { en: 'Content Liked', fr: 'Contenu aimé', es: 'Contenido gustado', ar: 'المحتوى المفضل' },
    'Member Since': { en: 'Member Since', fr: 'Membre depuis', es: 'Miembro desde', ar: 'عضو منذ' },
    'Live': { en: 'Live', fr: 'En direct', es: 'En vivo', ar: 'مباشر' },
    'Points': { en: 'Points', fr: 'Points', es: 'Puntos', ar: 'نقاط' },
    'pts': { en: 'pts', fr: 'pts', es: 'pts', ar: 'نقطة' },
    'games': { en: 'games', fr: 'jeux', es: 'juegos', ar: 'ألعاب' },
    'likes': { en: 'likes', fr: 'j\\'aimes', es: 'me gusta', ar: 'إعجابات' },
    'Next Rank': { en: 'Next Rank', fr: 'Prochain rang', es: 'Siguiente rango', ar: 'الرتبة التالية' },
    'Progress to Next Rank': { en: 'Progress to Next Rank', fr: 'Progression vers le prochain rang', es: 'Progreso al siguiente rango', ar: 'التقدم للرتبة التالية' },
    'points needed': { en: 'points needed', fr: 'points nécessaires', es: 'puntos necesarios', ar: 'النقاط المطلوبة' },
    'Achievements & Badges': { en: 'Achievements & Badges', fr: 'Réalisations et badges', es: 'Logros y medallas', ar: 'الإنجازات والشارات' },
    'Earned': { en: 'Earned', fr: 'Gagné', es: 'Ganado', ar: 'مكتسب' },
    'Locked': { en: 'Locked', fr: 'Verrouillé', es: 'Bloqueado', ar: 'مقفلة' },
    'Keep exploring to unlock more Badges!': { en: 'Keep exploring to unlock more Badges!', fr: 'Continuez à explorer pour débloquer plus de badges !', es: '¡Sigue explorando para desbloquear más insignias!', ar: 'استمر في الاستكشاف لفتح المزيد من الشارات!' },
    'Recent Activity': { en: 'Recent Activity', fr: 'Activité récente', es: 'Actividad reciente', ar: 'النشاط الأخير' },
    'Viewed': { en: 'Viewed', fr: 'Vu', es: 'Visto', ar: 'شوهد' },
    'How to level up?': { en: 'How to level up?', fr: 'Comment monter en niveau ?', es: '¿Cómo subir de nivel?', ar: 'كيف ترفع مستواك؟' },
    'Earn points by interacting with games: View (+5), Like (+5), Favorite (+2), and Download (+10). Unlocking ranks gives you special status in the community!': { en: 'Earn points by interacting with games: View (+5), Like (+5), Favorite (+2), and Download (+10). Unlocking ranks gives you special status in the community!', fr: 'Gagnez des points en interagissant avec les jeux : Vue (+5), J\\'aime (+5), Favoris (+2) et Téléchargement (+10). Débloquer des rangs vous donne un statut spécial !', es: 'Gana puntos interactuando con juegos: Ver (+5), Me gusta (+5), Favorito (+2) y Descargar (+10). ¡Desbloquear rangos te da un estado especial!', ar: 'اربح النقاط من خلال التفاعل مع الألعاب: مشاهدة (+5)، إعجاب (+5)، مفضلة (+2)، وتنزيل (+10). فتح الرتب يمنحك مكانة خاصة في المجتمع!' },
    'Cub Wolf': { en: 'Cub Wolf', fr: 'Loupceau', es: 'Lobo Cachorro', ar: 'شبل الذئب' },
    'Pup Wolf': { en: 'Pup Wolf', fr: 'Jeune Loup', es: 'Lobo Joven', ar: 'جرو الذئب' },
    'Juvenile Wolf': { en: 'Juvenile Wolf', fr: 'Loup Juvénile', es: 'Lobo Juvenil', ar: 'ذئب يافع' },
    'Subordinate Wolf': { en: 'Subordinate Wolf', fr: 'Loup Subalterne', es: 'Lobo Subordinado', ar: 'ذئب تابع' },
    'Beta Wolf': { en: 'Beta Wolf', fr: 'Loup Bêta', es: 'Lobo Beta', ar: 'ذئب بيتا' },
    'Alpha Wolf': { en: 'Alpha Wolf', fr: 'Loup Alpha', es: 'Lobo Alfa', ar: 'ذئب ألفا' },
    'First Blood': { en: 'First Blood', fr: 'Premier Sang', es: 'Primera Sangre', ar: 'أول قطرة دم' },
    'Explorer': { en: 'Explorer', fr: 'Explorateur', es: 'Explorador', ar: 'مستكشف' },
    'Enthusiast': { en: 'Enthusiast', fr: 'Enthousiaste', es: 'Entusiasta', ar: 'متحمس' },
    'Critic': { en: 'Critic', fr: 'Critique', es: 'Crítico', ar: 'ناقد' },
    'Fanboy': { en: 'Fanboy', fr: 'Fanboy', es: 'Fanático', ar: 'معجب' },
    'Rising Pup': { en: 'Rising Pup', fr: 'Chiot Montant', es: 'Cachorro en Ascenso', ar: 'جرو صاعد' },
    'Loyal Member': { en: 'Loyal Member', fr: 'Membre Fidèle', es: 'Miembro Leal', ar: 'عضو مخلص' },
    'The Alpha': { en: 'The Alpha', fr: 'L\\'Alpha', es: 'El Alfa', ar: 'الألفا' },
    'View your first game': { en: 'View your first game', fr: 'Voir votre premier jeu', es: 'Ver tu primer juego', ar: 'شاهد لعبتك الأولى' },
    'View 10 different games': { en: 'View 10 different games', fr: 'Voir 10 jeux différents', es: 'Ver 10 juegos diferentes', ar: 'شاهد 10 ألعاب مختلفة' },
    'View 50 different games': { en: 'View 50 different games', fr: 'Voir 50 jeux différents', es: 'Ver 50 juegos diferentes', ar: 'شاهد 50 لعبة مختلفة' },
    'Like your first game': { en: 'Like your first game', fr: 'Aimer votre premier jeu', es: 'Dar me gusta a tu primer juego', ar: 'أعجب بلعبتك الأولى' },
    'Like 10 games': { en: 'Like 10 games', fr: 'Aimer 10 jeux', es: 'Dar me gusta a 10 juegos', ar: 'أعجب بـ 10 ألعاب' },
    'Reach Pup Wolf rank': { en: 'Reach Pup Wolf rank', fr: 'Atteindre le rang Jeune Loup', es: 'Alcanzar el rango Lobo Joven', ar: 'الوصول إلى رتبة جرو الذئب' },
    'Earn 100,000 points': { en: 'Earn 100,000 points', fr: 'Gagner 100 000 points', es: 'Ganar 100.000 puntos', ar: 'اربح 100,000 نقطة' },
    'Reach Alpha Wolf rank': { en: 'Reach Alpha Wolf rank', fr: 'Atteindre le rang Loup Alpha', es: 'Alcanzar el rango Lobo Alfa', ar: 'الوصول إلى رتبة ذئب ألفا' },
    'No recent activity yet. Go explore some games!': { en: 'No recent activity yet. Go explore some games!', fr: 'Aucune activité récente. Allez explorer des jeux !', es: 'Aún no hay actividad reciente. ¡Ve a explorar algunos juegos!', ar: 'لا يوجد نشاط أخير بعد. اذهب لاستكشاف بعض الألعاب!' },`;

if (!code.includes("'Visitor Profile'")) {
    code = code.replace(target, newTranslations);
    fs.writeFileSync('src/contexts/LanguageContext.tsx', code);
}
